ci: add unit tests

diff --git a/.github/workflows/unit-test.yml b/.github/workflows/unit-test.yml
--- a/.github/workflows/unit-test.yml
+++ b/.github/workflows/unit-test.yml
@@ -1,4 +1,4 @@
-name: GitHub Actions Demo
+name: Unit Tests
 on:
   push:
     branches: [main]
@@ -16,10 +16,12 @@ jobs:
           cache: npm
       - name: Install
         run: npm ci
-      - name: Lint
+      - name: Test
         run: npm run test:ci
-      - name: Publish Test Results
-        uses: EnricoMi/publish-unit-test-result-action@v1
-        if: always()
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
         with:
-          files: "test-results.xml"
+          name: Unit Tests            # Name of the check run which will be created
+          path: test-results.xml    # Path to test results
+          reporter: jest-junit        # Format of test results
